version: '3.9'

services:
  401k-calculator-app:
    stdin_open: true
    tty: true
    container_name: 401k-calculator-app
    build: .
    entrypoint: ["/app/401k_calculator"]
    environment:
      DATABASE_URL: "host=401k_calculator_db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - 401k_calculator_db
  401k_calculator_db:
    container_name: 401k_calculator_db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}